# pnpm-workspace.yaml (chỉ ở root)
packages:
  - "frontend"
  - "backend/*"
  - "packages/*"
catalog:
  "prisma": ^7.10.0
  "@prisma/client": ^7.10.0
allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": true
  base64: true
  bcrypt: true
  compress-buffer: true
  esbuild: true
  hiredis: true
  iconv: true
  msgpackr-extract: true
  pg: true
  prisma: true
  stacktrace: true
  unrs-resolver: true
  uriparser: true
  workerd: true
