# pnpm-workspace.yaml (chỉ ở root)
packages:
  - "frontend/*"
  - "backend/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  base64: true
  compress-buffer: true
  hiredis: true
  iconv: true
  pg: true
  prisma: true
  stacktrace: true
  unrs-resolver: true
  uriparser: true
