export const DomainErrorCode = {
  USERNAME_INVALID_CHARS: 'USERNAME_INVALID_CHARS',
  USERNAME_RESERVED: 'USERNAME_RESERVED',
  USERNAME_CHANGE_COOLDOWN: 'USERNAME_CHANGE_COOLDOWN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_USED_DETECTED: 'TOKEN_USED_DETECTED',
} as const;

export type AppErrorCodeType =
  (typeof DomainErrorCode)[keyof typeof DomainErrorCode];
